name: Checkstyle Obedience

on:
  pull_request:
    branches: [ develop ]
    types: [ opened, synchronize, reopened ]

jobs:
  checkstyle:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write 

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Perform Checkstyle with Check Reporter
        uses: dbelyaev/action-checkstyle@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          checkstyle_config: .github/config/checkstyle.xml
          checkstyle_version: 10.12.5
          reporter: github-pr-check
          level: error

      - name: Perform Checkstyle with Review Reporter
        uses: dbelyaev/action-checkstyle@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          checkstyle_config: .github/config/checkstyle.xml
          checkstyle_version: 10.12.5
          reporter: github-pr-review
